-- this is a joke!
rconsolename("Account Stealer")
rconsoleprint("@@RED@@")
rconsoleprint("Spoofing Token... \n")
wait(math.random(1, 5))
rconsoleprint("Stealing Password... \n")
wait(math.random(1, 5))
rconsoleprint("Sending... \n")
wait(math.random(1, 5))
rconsoleprint("Transferring Account... \n")
wait(math.random(1, 5))
rconsoleprint("@@GREEN@@")
rconsoleprint("Account Successfully Stolen! \n")
